def libVersion = "v0.26.0"

ext {
    extName = 'NewPipe'
    extClass = '.NewPipeFactory'
    extVersionCode = 1
    containsNsfw = false
}

apply from: "$rootDir/common.gradle"

dependencies {
    //noinspection UseTomlInstead
    implementation("com.github.teamnewpipe:NewPipeExtractor:$libVersion")
    //noinspection UseTomlInstead
    compileOnly("androidx.preference:preference-ktx:1.2.1")
}

android {
    defaultConfig {
        buildConfigField "String", "LIB_VERSION", "\"${libVersion}\""
    }
}